### ISSUE TITLE
Search results encoding: asian/arabic characters not displayed

### ISSUE THREAD

**Issue by Laura-O** [cubing/worldcubeassociation.org#521] opened 2016-04-21 11:38 UTC
Screenshot:
![bildschirmfoto 2016-04-21 um 13 36 36](https://cloud.githubusercontent.com/assets/362249/14707667/1885b1d2-07c6-11e6-9263-ca07fb719aba.png)

(Browser: Chrome 49.X on OS X 10.11)

**Comment by jfly** [comment] 2016-04-21 15:54
Duplicate of https://github.com/cubing/worldcubeassociation.org/issues/238.

Thanks for the report, Laura!

**Closed by jfly** 2016-04-21 15:54 UTC
