### ISSUE TITLE
Country names are shown inconsistenly

### ISSUE THREAD

**Issue by Luis-J-Ianez** [cubing/worldcubeassociation.org#666] opened 2016-05-24 07:06 UTC
Seems that country names are shown as Countries.id and Countries.name inconsistently.  Apart from the fictional countries we have (X? - Multiple Countries (?)), this is only a problem with "Cote d_Ivoire" and "Cote d'Ivoire".  Some URLs where the bug can be seen:

https://www.worldcubeassociation.org/competitions/NationalCapitalRegion2016/results/all
https://www.worldcubeassociation.org/competitions/NationalCapitalRegion2016/results/by_person
https://www.worldcubeassociation.org/results/events.php?eventId=333&regionId=Cote%2Bd_Ivoire&years=&show=100%2BPersons&single=Single

**Comment by jonatanklosko** [comment] 2016-05-24 11:01
The fix is pretty straightforward. What's the issue with the last link? If you think about the coubtry id in the url itself, I don't consider this to be wrong.

**Comment by Luis-J-Ianez** [comment] 2016-05-24 11:06
No, the table header says "Rubik's Cube          Cote d_Ivoire          100 Persons"

**Comment by jonatanklosko** [comment] 2016-05-24 11:43
Oh, I missed that.
So this one is caused by a global method used in the PHP code, see [here](https://github.com/cubing/worldcubeassociation.org/blob/5fe5e5c1557c4d5e7d2b49d4caeb585f60e4c2ed/webroot/results/includes/_framework.php#L136-L140). But I don't know how to fix this safely.

**Comment by larspetrus** [comment] 2016-05-24 14:53
So this bug has always been there?

On Tue, May 24, 2016 at 4:43 AM, Jonatan Kłosko <notifications@github.com>
wrote:

> Oh, I missed that.
> So this one is caused by a global method used in the PHP code, see here
> <https://github.com/cubing/worldcubeassociation.org/blob/5fe5e5c1557c4d5e7d2b49d4caeb585f60e4c2ed/webroot/results/includes/_framework.php#L136-L140>.
> But I don't know how to fix this safely.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cubing/worldcubeassociation.org/issues/666#issuecomment-221243847>
>



-- 
Procrastinators - the Leaders of Tomorrow

**Comment by jonatanklosko** [comment] 2016-05-24 14:56
I think so. Actually it's not surprising that no one has caught this because there's only one real country which may cause a problem and there are only two people from 'Cote d'Ivoire' that have ever competed.

**Comment by jonatanklosko** [comment] 2016-05-24 20:11
Closing via #667
It's already deployed!

**Closed by jonatanklosko** 2016-05-24 20:11 UTC
Labels: bug
